query MediaTopChart($page: Int, $perPage: Int, $type: MediaType, $sort: [MediaSort]) {
    Page(page: $page, perPage: $perPage) {
        media(type: $type, sort: $sort) {
            id
            title {
                userPreferred
            }
            seasonYear
            meanScore
            coverImage {
                large
            }
            averageScore
            studios(isMain: true) {
                nodes {
                    name
                }
            }
            format
        }
        pageInfo {
            currentPage
            hasNextPage
        }
    }
}